export const DEFAULT_MAX_TOOL_ITERATIONS = 3;
export const DEFAULT_TOOL_CALL_TIMEOUT_MS = 15000;
export const DEFAULT_TEMPERATURE = 0.7;
export const DEFAULT_MAX_OUTPUT_TOKENS = 512;
export const DEFAULT_LORE_TOKEN_BUDGET = 1024;
